/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.26                          *
*        Compiled Aug  8 2014, 14:49:54                              *
*        (c) 2013 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "AD9854.h"
#include "math.h"
#include "adc.h"
#include "includes.h"
#include "GRAPH.h"
#include "stdlib.h"
#include "stdio.h"
#include "ctype.h"
#include "usart.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x00)
#define ID_GRAPH_0   (GUI_ID_USER + 0x01)
#define ID_EDIT_0   (GUI_ID_USER + 0x02)
#define ID_EDIT_1   (GUI_ID_USER + 0x03)
#define ID_TEXT_0   (GUI_ID_USER + 0x04)
#define ID_TEXT_1   (GUI_ID_USER + 0x05)
#define ID_TEXT_2   (GUI_ID_USER + 0x06)
#define ID_TEXT_3   (GUI_ID_USER + 0x07)
#define ID_EDIT_2   (GUI_ID_USER + 0x08)
#define ID_TEXT_4   (GUI_ID_USER + 0x09)
#define ID_TEXT_5   (GUI_ID_USER + 0x0A)
#define ID_BUTTON_0   (GUI_ID_USER + 0x0B)
#define ID_EDIT_3   (GUI_ID_USER + 0x0C)
#define ID_TEXT_6   (GUI_ID_USER + 0x0D)
#define ID_TEXT_7   (GUI_ID_USER + 0x0E)
#define ID_TEXT_8   (GUI_ID_USER + 0x0F)
#define ID_EDIT_4   (GUI_ID_USER + 0x10)
#define ID_BUTTON_1   (GUI_ID_USER + 0x11)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
static GRAPH_SCALE_Handle hScaleH;//水平刻度句柄
static GRAPH_SCALE_Handle hScaleV;//垂直刻度句柄
//static GRAPH_DATA_Handle pdataGRP;//数据句柄
int mod=4;//标志基础任务和发挥任务的模式，初始为3，不进入其他状态
static GUI_POINT _aPoint[1];//输入数据为点阵（包含横坐标x,纵坐标y的结构体）
extern int ADC_store_PP[200];
static GRAPH_DATA_Handle hDataXY;
char s2show[10];
extern int Gain_graph[200];
extern int ADC_store_P[200];
extern int ADC_store_N[200];
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Circuit Tester", ID_FRAMEWIN_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { GRAPH_CreateIndirect, "Graph", ID_GRAPH_0, 0, 0, 620, 441, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_0, 630, 31, 120, 32, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_1, 630, 96, 120, 32, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Input Resistance", ID_TEXT_0, 636, 5, 110, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Output Resistance", ID_TEXT_1, 633, 75, 120, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "ohm", ID_TEXT_2, 755, 36, 29, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "ohm", ID_TEXT_3, 752, 100, 37, 20, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_2, 629, 158, 120, 32, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Gain", ID_TEXT_4, 648, 134, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "V/V", ID_TEXT_5, 750, 164, 38, 20, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Part A", ID_BUTTON_0, 643, 258, 100, 32, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_3, 630, 213, 120, 32, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "fc", ID_TEXT_6, 650, 190, 80, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "kHz", ID_TEXT_7, 751, 218, 39, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Fault Diagnosis", ID_TEXT_8, 617, 297, 167, 33, 0, 0x0, 0 },
  { EDIT_CreateIndirect, "Edit", ID_EDIT_4, 630, 329, 120, 32, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "Part B", ID_BUTTON_1, 643, 380, 100, 32, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
//static void _InitPoints(void)
//{
//	int count_size=0;
//	for(count_size = 0;count_size<200;count_size++)
//	{
//		_aPoint[count_size].x=count_size;
//		_aPoint[count_size].y=200;
//		//printf("%d\n",ADC_store[count_size]);
//	}
//}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Circuit Tester'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetTitleHeight(hItem, 40);
    FRAMEWIN_SetFont(hItem, GUI_FONT_32B_ASCII);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem, "");
    EDIT_SetFont(hItem, GUI_FONT_24B_ASCII);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_1);
    EDIT_SetText(hItem, "");
    EDIT_SetFont(hItem, GUI_FONT_24B_ASCII);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Input Resistance'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_16B_ASCII);
    //
    // Initialization of 'Output Resistance'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, GUI_FONT_16B_ASCII);
    //
    // Initialization of 'ohm'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, GUI_FONT_16B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'ohm'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetFont(hItem, GUI_FONT_16B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_2);
    EDIT_SetText(hItem, "");
    EDIT_SetFont(hItem, GUI_FONT_24B_ASCII);
    //
    // Initialization of 'Gain'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_16B_ASCII);
    //
    // Initialization of 'V/V'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem, GUI_FONT_16B_ASCII);
    //
    // Initialization of 'Part A'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_3);
    EDIT_SetText(hItem, "");
    EDIT_SetFont(hItem, GUI_FONT_24B_ASCII);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'fc'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
    TEXT_SetFont(hItem, GUI_FONT_16B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'kHz'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
    TEXT_SetFont(hItem, GUI_FONT_16B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Fault Diagnosis'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
    TEXT_SetFont(hItem, GUI_FONT_16B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_4);
    EDIT_SetText(hItem, "None");
    EDIT_SetFont(hItem, GUI_FONT_24B_ASCII);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Part B'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
    // USER START (Optionally insert additional code for further widget initialization)
		//Graph画图
		hItem = WM_GetDialogItem(pMsg->hWin, ID_GRAPH_0);
    GRAPH_SetBorder(hItem, 40, 0, 0, 30);//设置画图的边框
	
		hScaleV = GRAPH_SCALE_Create(30,GUI_TA_RIGHT,GRAPH_SCALE_CF_VERTICAL,25);//设置垂直范围的尺度标签，每25像素一个点
		GRAPH_SCALE_SetTextColor(hScaleV,GUI_RED);//刻度颜色为红色
		GRAPH_AttachScale(hItem,hScaleV);//垂直刻度
		GRAPH_SCALE_SetFactor(hScaleV,0.4);//垂直刻度比例尺
		GRAPH_SCALE_SetNumDecs(hScaleV,1);//小数点
	
		hScaleH = GRAPH_SCALE_Create(415,GUI_TA_HCENTER,GRAPH_SCALE_CF_HORIZONTAL,50);//设置水平范围的尺度标签，100KHZ分辨率
		GRAPH_SCALE_SetTextColor(hScaleH,GUI_RED);
		GRAPH_AttachScale(hItem,hScaleH);
		GRAPH_SCALE_SetFactor(hScaleH,0.01);//设置横坐标比例
		//GRAPH_SCALE_SetOff(hScaleH,-750);//设置横坐标偏移(右移为正，左移为负，其中偏移的值要考虑比例尺）
		GRAPH_SCALE_SetNumDecs(hScaleH,1);//设置小数点后显示的位数
	
		//pdataGRP = GRAPH_DATA_XY_Create(GUI_GREEN,200,0,0);//这里频谱需要改成XY
		//GRAPH_AttachData(hItem,pdataGRP);
		hDataXY = GRAPH_DATA_XY_Create(GUI_GREEN,200,0,0);//将AD采样的数据添加到图像中
		GRAPH_AttachData(hItem,hDataXY);
		
		GRAPH_SetGridDistY(hItem,25);
		GRAPH_SetGridFixedX(hItem,1);
		
		GRAPH_SetGridVis(hItem,1);
		
		//GUI_DispBinAt(Input, 0,0, 8);
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_EDIT_0: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_1: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_2: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'Part A'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
			//先扫频，再保持1k点频
					mod=0;//0标志着先进行一次扫频再进行电频
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_3: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_EDIT_4: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Part B'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
			//粗略扫频，再加1k电频，测量出当前状态下的输入输出电阻
				mod=2;//mod=2在主函数进入发挥部分的代码
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
	//增加一个软件定时器，用来采样DAC，判断
		case WM_TIMER://软件定时器部分
			if(WM_IsCompletelyCovered(pMsg->hWin)) break;
			if(mod == 3)
			{
				//printf("%d\n",mod);
				//_InitPoints();
				int count_size=0;
				for(count_size=0;count_size<200;count_size++)
				{
				_aPoint[0].x=count_size*2;
				_aPoint[0].y=((ADC_store_P[count_size]-ADC_store_N[count_size])/50*3);
				GRAPH_DATA_XY_AddPoint(hDataXY,_aPoint);
				//printf("ADC=%d\n",ADC_store_P[count_size]);
				//printf("ADC_N=%d\n",ADC_store_N[count_size]);
				}
					//GRAPH_DATA_XY_AddPoint(pdataGRP,_aPoint);
			}
			//hItem = WM_GetDialogItem(pMsg -> hWin, ID_EDIT_0);
			//EDIT_AddKey(hItem,+48);
			//itoa(ADC_store[10],s2show,10);
			//EDIT_SetText(hItem,s2show);
			//延时函数
			WM_RestartTimer(pMsg->Data.v,3000);
			break;
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateCircuit Tester
*/
WM_HWIN CreateFramewin(void);
WM_HWIN CreateFramewin(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
	WM_CreateTimer(WM_GetClientWindow(hWin),1,3000,0);//创建一个软件定时器
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
